<Project Sdk="Aspire.AppHost.Sdk/13.0.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>8de523c7-9251-40ea-ad99-738d99fcbc57</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Aspire.Hosting.Docker" />
	  <PackageReference Include="Aspire.Hosting.PostgreSQL" />
	  <PackageReference Include="Aspire.Hosting.RabbitMQ" />
	  <PackageReference Include="Aspire.Hosting.Yarp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KPO_HW4.OrderService\KPO_HW4.OrderService.csproj" />
    <ProjectReference Include="..\KPO_HW4.PaymentsService\KPO_HW4.PaymentsService.csproj" />
    <ProjectReference Include="..\KPO_HW4.Ui\KPO_HW4.Ui.csproj" />
  </ItemGroup>

</Project>
