// <auto-generated />
using System;
using KPO_HW3.FileAnalysisService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KPO_HW3.FileAnalysisService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AnalysisDbContext))]
    [Migration("20251211122951_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KPO_HW3.FileAnalysisService.Infrastructure.Data.Entities.PlagiarismReport", b =>
                {
                    b.Property<Guid>("WorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("SimilarityScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("WorkId");

                    b.ToTable("PlagiarismReports");
                });

            modelBuilder.Entity("KPO_HW3.FileAnalysisService.Infrastructure.Data.Entities.PlagiarismReport", b =>
                {
                    b.OwnsMany("KPO_HW3.FileAnalysisService.Infrastructure.Data.Entities.PlagiarismReportMatch", "Matches", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("MatchedWorkId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ReportWorkId")
                                .HasColumnType("uuid");

                            b1.Property<double>("SimilarityScore")
                                .HasColumnType("double precision");

                            b1.HasKey("Id");

                            b1.HasIndex("ReportWorkId");

                            b1.ToTable("PlagiarismReportMatch");

                            b1.WithOwner()
                                .HasForeignKey("ReportWorkId");
                        });

                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
