<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:10.0</ContainerBaseImage>
    <UserSecretsId>943ad532-b4e0-4a65-9127-967aab322e49</UserSecretsId>
  </PropertyGroup>


	<ItemGroup>
		<ContainerPort Include="8081" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KPO_HW4.ServiceDefaults\KPO_HW4.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
