<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:10.0</ContainerBaseImage>
		<UserSecretsId>56a8b483-cd06-414c-9e6a-9cf44339affc</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="CommunityToolkit.Aspire.Minio.Client" />
		<PackageReference Include="DotNext" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\KPO_HW3.ServiceDefaults\KPO_HW3.ServiceDefaults.csproj" />
	</ItemGroup>

</Project>
